name: Deploy to Firebase Hosting (production)
on:
  release:
    types: [published]

permissions:
  contents: read # only reading the ZIP asset
  id-token: write # if you use OIDC runs-to-GCP

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Download `dist.zip`
        run: |
          ASSET_ID=$(gh release view "${{ github.event.release.tag_name }}" \
            --repo "${{ github.repository }}" \
            --json assets --jq '.assets[] | select(.name=="dist.zip") | .id')
          gh release download "${{ github.event.release.tag_name }}" \
            --repo "${{ github.repository }}" \
            --pattern dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip `dist.zip`
        run: unzip dist.zip -d .

      - name: Deploy to live channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: howufeelin-6c920
          channelId: live
